export const texte = {
    subtitle: ('Ökologischer Landbau aus Leidenschaft'),
    ackerbau_titel: 'Ackerbau',
    huehner: 'Seit Ende diesen Jahres gibt es auf unserem Hof ein Hühnermobil, in welchem eine kleine Hühnerschar ein zu Hause gefunden hat. Der Vorteil der mobilen Hühnerhaltung gegenüber der normalen Freilandhaltung ist, dass der Grünauslauf vor dem Stall nicht überdüngt wird und der Parasitendruck für die Tiere geringer ist, da der Stall in regelmäßigen Abständen umgestellt wird. Außerdem haben die Hühner dadurch jedes Mal einen neuen frischen Grünauslauf, in dem sie sich nach Belieben austoben können. Als Dank für diese Haltungsform legt jedes unserer Hühner fast jeden Tag ein Ei!',
    schweine: 'Unsere Schweine kaufen wir als Ferkel von einem Biolandbetrieb aus der Region zu. Auf unserem Betrieb angekommen, erwartet die Schweine ein komfortabler Stall, welcher mit reichlich Stroh eingestreut ist. Außerdem haben unsere Schweine jederzeit die Möglichkeit ins freie zu gehen, das an unseren Ställen ein Auslauf angegliedert ist, welcher ebenfalls mit Stroh eingestreut ist. Hier haben die Tiere die Möglichkeit das Außenklima zu genießen. Zusätzlich bieten wir unseren Tieren im Auslauf frische Kleegrassilage an, welche wir von unsren Ackerflächen ernten. Zusätzlich zu dem Kleegras erhalten unsere Schweine eine Getreidemischung, welche wir auch größtenteils aus unseren eigenen Futtermitteln selbst herstellen!',
    ackerbau: 'Als weiter Betriebszweig zu der Tierhaltung gehört der Ackerbau zu unserem Betrieb. Mit Hilfe unserer vielfältigen Fruchtfolge, schaffen wir es die natürliche Fruchtbarkeit des Bodens zu erhalten und auf chemische Pflanzenschutzmittel, sowie Mineralische Düngemittel zu verzichten. In unserer Fruchtfolge bauen wir unter anderem Kleegras, Ackerbohnen, Erbsen und verschiedene Getreidesorten wie Weizen, Gerste, Hafer und Triticale an, welche wir allesamt auf unserem Betrieb lagern und als Futtermittel für unsere Tiere verwenden. Zusätzlich zu unseren Hauptkulturen bauen wir verschiedene Zwischenfruchtmischungen an, welche sich positiv auf den Boden auswirken und als Nahrungsquelle für verschiedenste Insekten dienen.',
    verkauf: 'Vorne an unserer Hofeinfahrt befindet sich ein kleines Verkaufshäuschen, in welchem sie täglich die frisch gelegten Eier aus unserem Hühnermobil kaufen können. Unsere Verkaufshütte ist rund um die Uhr geöffnet!',
    ueber_uns: 'Herzlich willkommen auf der Website unseres Betriebes. Wir hoffen euch hier einen kleinen Einblick in unseren Betrieb geben zu können. Auf unserem vielseitigen Biohof in Dahl leben wir zusammen mit Schweinen, Hühnern und unserem Hofhund. Neben der Tierhaltung betreiben wir noch Ackerbau, welcher für die Kreislaufwirtschaft in unserem Betrieb wichtig ist. All das geschieht nach den strengen Richtlinien des Bioland-Verbandes, bei welchem wir seit 2001 Mitglied sind!',
}
