export const texte = {
    subtitle: ('Ökologischer Landbau aus Leidenschaft'),
    ackerbau_titel: 'Ackerbau',
    huehner: 'Seit Ende 2019 gibt es auf unserem Hof ein Hühnermobil, in dem eine kleine Hühnerschar ein Zuhause gefunden hat. Der Vorteil der mobilen Hühnerhaltung gegenüber der normalen Freilandhaltung ist, dass der Grünauslauf vor dem Stall nicht überdüngt wird und der Parasitendruck für die Tiere geringer ist, da der Stall in regelmäßigen Abständen umgestellt wird. Außerdem haben die Hühner dadurch jedes Mal einen neuen frischen Grünauslauf, in dem sie sich nach Belieben austoben können. Das wirkt sich natürlich auf den Geschmack und die Qualität der Eier aus. Als Dank für diese Haltungsform legt jedes unserer Hühner fast jeden Tag ein Ei!',
    schweine: 'Unsere Schweine kaufen wir als Ferkel von einem befreundeten Biolandbetrieb aus der Region zu. Auf unserem Betrieb angekommen, erwartet die Schweine ein komfortabler Stall, der mit reichlich Stroh eingestreut ist und den Schweinen viel Platz bietet. Außerdem haben unsere Schweine jederzeit die Möglichkeit nach draußen zu gehen, da an unseren Ställen ein großzügiger eingestreuter Auslauf angegliedert ist. Hier haben die Tiere die Möglichkeit das Außenklima zu genießen, was sie auch ausgiebig tun. Auch bei Schnee und Regen sind immer Schweine draußen. Im Auslauf steht unseren Tieren jederzeit frische Kleegrassilage zur Verfügung, die von den Schweinen gerne und in großer Menge gefressen wird. Zusätzlich zu dem Kleegras erhalten unsere Schweine eine Getreidemischung, welche wir auch größtenteils aus den Futtermitteln vom eigenen Acker selbst herstellen.',
    ackerbau: 'Die Grundlage unserer Biolandwirtschaft ist der Ackerbau, denn hier werden die Futtermittel für unsere Tiere erzeugt. Mit Hilfe unserer vielfältigen Fruchtfolge schaffen wir es die natürliche Fruchtbarkeit des Bodens zu erhalten und ohne chemische Pflanzenschutzmittel und mineralische Düngemittel wertvolle Nahrungsmittel zu erzeugen. Unsere Fruchtfolge besteht unter anderem aus Kleegras, Ackerbohnen, Erbsen und verschiedenen Getreidesorten wie Weizen, Gerste, Hafer und Triticale, die wir allesamt auf unserem Betrieb lagern und als Futtermittel für unsere Tiere verwenden. Zusätzlich zu unseren Hauptkulturen bauen wir verschiedene Zwischenfruchtmischungen an, welche sich positiv auf den Boden auswirken und als Nahrungsquelle für verschiedenste Insekten dienen.',
    verkauf: 'Direkt an unserer Hofeinfahrt haben wir eine Verkaufshütte gebaut, in der Sie täglich die frisch gelegten Eier aus unserem Hühnermobil kaufen können. Vielleicht werden in Zukunft noch weitere Produkte aus unserer Biolandwirtschaft dazu kommen. Wenn Sie eine Idee haben - sprechen Sie uns an! Unsere Verkaufshütte ist übrigens rund um die Uhr geöffnet, auch an Sonn- und Feiertagen!',
    ueber_uns: 'Herzlich willkommen auf der Website unseres Biohofs. Wir möchten Ihnen hier einen kleinen Einblick in unseren Betrieb geben. Auf unserem vielseitigen Biohof in Paderborn-Dahl leben wir zusammen mit Schweinen, Hühnern und unserem Hofhund Barney. Neben der Tierhaltung betreiben wir noch Ackerbau, der die Grundlage für die Kreislaufwirtschaft in unserem Betrieb ist. All das geschieht nach den strengen Richtlinien des Bioland-Verbandes, bei dem wir seit 2002 Mitglied sind!',
}
